[package]
name = "chia-block-listener"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# NAPI-rs for Node.js bindings
napi = { version = "2", features = ["napi9", "tokio_rt", "async"] }
napi-derive = "2"

# Async runtime
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"

# Chia-related dependencies
chia-protocol = { version = "0.21", features = ["py-bindings"] }
chia-bls = "0.21"
chia-wallet-sdk = "0.27"
clvm-traits = "0.21"
clvmr = "0.8"
chia_rs = "0.21"

# Networking
tokio-tungstenite = { version = "0.27", features = ["rustls-tls-native-roots"] }
rustls = { version = "0.21", features = ["dangerous_configuration"] }
rustls-native-certs = "0.6"
rustls-pemfile = "2"
futures-util = "0.3"

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = "1"
hex = "0.4"

# Utilities
anyhow = "1"
thiserror = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
once_cell = "1"

# Database
rusqlite = { version = "0.32", features = ["bundled"] }

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
