name: Dependency Update

on:
  schedule:
    # Run every Monday at 9am UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Update dependencies
      id: update
      run: |
        # Update dependencies to latest versions
        npm update --save
        
        # Update dev dependencies
        npm update --save-dev
        
        # Check if there are changes
        if git diff --quiet package.json package-lock.json; then
          echo "No updates available"
          echo "has_updates=false" >> $GITHUB_OUTPUT
        else
          echo "Updates available"
          echo "has_updates=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Run tests with updated dependencies
      if: steps.update.outputs.has_updates == 'true'
      run: |
        npm ci
        npm test
        npm run build
    
    - name: Create Pull Request
      if: steps.update.outputs.has_updates == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore(deps): update dependencies'
        title: 'chore(deps): update dependencies'
        body: |
          ## Automated Dependency Update
          
          This PR updates the project dependencies to their latest versions.
          
          ### Changes
          - Updated production dependencies
          - Updated development dependencies
          
          ### Checklist
          - [x] All tests pass
          - [x] Build succeeds
          - [ ] Manual testing completed
          
          Please review the changes and ensure everything works as expected.
        branch: deps/update-dependencies
        delete-branch: true
        labels: |
          dependencies
          automated

  check-vulnerabilities:
    name: Check for Vulnerabilities
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run security audit
      id: audit
      run: |
        # Run audit and capture output
        npm audit --json > audit-report.json || true
        
        # Check for high or critical vulnerabilities
        HIGH_VULNS=$(jq '.metadata.vulnerabilities.high' audit-report.json)
        CRITICAL_VULNS=$(jq '.metadata.vulnerabilities.critical' audit-report.json)
        
        if [ "$HIGH_VULNS" -gt 0 ] || [ "$CRITICAL_VULNS" -gt 0 ]; then
          echo "Found high or critical vulnerabilities"
          echo "has_vulnerabilities=true" >> $GITHUB_OUTPUT
        else
          echo "No high or critical vulnerabilities found"
          echo "has_vulnerabilities=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Try to fix vulnerabilities
      if: steps.audit.outputs.has_vulnerabilities == 'true'
      run: |
        npm audit fix --force
        
        # Run audit again to check if fixed
        npm audit
    
    - name: Create vulnerability report issue
      if: steps.audit.outputs.has_vulnerabilities == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const report = JSON.parse(fs.readFileSync('audit-report.json', 'utf8'));
          
          const issueBody = `
          ## Security Vulnerability Report
          
          npm audit has found the following vulnerabilities:
          
          - **Critical**: ${report.metadata.vulnerabilities.critical}
          - **High**: ${report.metadata.vulnerabilities.high}
          - **Moderate**: ${report.metadata.vulnerabilities.moderate}
          - **Low**: ${report.metadata.vulnerabilities.low}
          
          Please review and update the affected dependencies.
          
          \`\`\`json
          ${JSON.stringify(report.advisories, null, 2)}
          \`\`\`
          `;
          
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Security: Vulnerabilities detected in dependencies',
            body: issueBody,
            labels: ['security', 'dependencies']
          });